### ISSUE TITLE
Bug in Return/Checkout Movies

### ISSUE THREAD

**Issue by kedarkhetia** [usfcs-perf-eng-s20/heroku-project-favs#18]
I was checking some random APIs and found that return movies is not working as expected.

For Example, I checked out a movie using 
```
Endpoint: https://hist-fav-checkout-beta.herokuapp.com/checkOutMovies
{
	"userId" : 1,
	"movieId" : 5
}

```

And it returned success, then I tried return movies for same, 

```
Endpoint: https://hist-fav-checkout-beta.herokuapp.com/returnMovie
{
	"userId" : 1,
	"movieId" : 5
}

```
and it gave below error,

```
{
    "confirm": false,
    "message": "Either user or movie is not present/invalid"
}
```

I suspect that the issue is we are checking if the inventory is present or not in return movies and checkout movies, but we are not updating it anywhere.

CheckoutMovies: https://github.com/usfcs-perf-eng-s20/heroku-project-favs/blob/master/src/cs/usfca/edu/histfavcheckout/controller/HistFavCheckoutHandler.java#L250-L253

ReturnMovies: https://github.com/usfcs-perf-eng-s20/heroku-project-favs/blob/master/src/cs/usfca/edu/histfavcheckout/controller/HistFavCheckoutHandler.java#L341-L343

Not sure what should be our next steps to resolve this issue. Possible suggestion is while checking out a movie id, if the movieId is valid we should add an entry to inventory table with some initial value of totalNumberOfCopies and availableCopies = totalNumberOfCopies - 1

**Comment by kedarkhetia** [comment]
Checked DB after checkout for movieId=111632, inventory is being updated in inventory table.

hist-fav-checkout-beta::DATABASE=> select * from inventory where product_id=111632;
 product_id | available_copies | total_number_of_copies 
------------+------------------+------------------------
     111632 |               73 |                     74
(1 row)

**Comment by mosopeogundipe** [comment]
We currently decrement the number of checked out movies per [here](https://github.com/usfcs-perf-eng-s20/heroku-project-favs/blob/master/src/cs/usfca/edu/histfavcheckout/controller/HistFavCheckoutHandler.java#L261) and that is a correct behavior.

One fix we need to make in /checkOutMovies API is to add movies that don't exist in our inventory, but are contained in the Search Team's DB. When a user wants to check out such movies, we should add them with a default number of copies. This will be done by me @mosopeogundipe 

We also need to investigate why the /returnMovie API returns null for some cases, causing errors. This will be done by @ksonar

**Comment by ksonar** [comment]
With respect to `/returnMovie`, the issue has been resolved. There was some confusion as the request body was expected of `PrimaryKey`, but was tested by passing body of type` OperationalRequest`.

To maintain uniformity among our public APIs, the request body **now** has been changed to type `OperationalRequest`. This update has been tested and pushed to the branch `feature-return-movie`
