### ISSUE TITLE
Change /returnMovies to /returnMovie and /checkOutMovies to /checkOutMovie in Authentication Filter

### ISSUE THREAD

**Issue by mosopeogundipe** [usfcs-perf-eng-s20/heroku-project-favs#20]
The path for the return movie API in the Authentication Filter is wrong. It's currently `/returnMovies` whereas it should be `/returnMovie` as can be seen in the "IncludeFilters.java" file [here](https://github.com/usfcs-perf-eng-s20/heroku-project-favs/blob/master/src/cs/usfca/edu/histfavcheckout/filters/IncludeFilters.java#L14)

We need to correct this so users can be authenticated when returning movies

**Comment by kedarkhetia** [comment]
I think we should also rename `checkOutMovies` to `checkOutMovie` (in api as well as filter) since it can just checkout a single movie at a time.

**Comment by mosopeogundipe** [comment]
Agreed, that makes sense
