### ISSUE TITLE
Enable CORS for our API

### ISSUE THREAD

**Issue by mosopeogundipe** [usfcs-perf-eng-s20/heroku-project-favs#23]
This is based on the request by the Web (FrontEnd) team. We need to enable CORS for our API. I'd say we do this at the [Controller ](https://github.com/usfcs-perf-eng-s20/heroku-project-favs/blob/master/src/cs/usfca/edu/histfavcheckout/controller/HistFavCheckoutController.java#L33) level, so it influences all the endpoints we have there.

**Comment by kedarkhetia** [comment]
Guide: https://spring.io/guides/gs/rest-service-cors/#controller-method-cors-configuration

As far as I know, if we do not mention `origins` in `@CrossOrigin` then it will allow CORS for any host.

**Comment by kedarkhetia** [comment]
Or a Global config should also work,

```
@Configuration
public class MyConfiguration {

    @Bean
    public WebMvcConfigurer corsConfigurer() {
        return new WebMvcConfigurerAdapter() {
            @Override
            public void addCorsMappings(CorsRegistry registry) {
                registry.addMapping("/**");
            }
        };
    }
}

```
Ref. https://spring.io/blog/2015/06/08/cors-support-in-spring-framework

**Comment by mosopeogundipe** [comment]
> 
> 
> Or a Global config should also work,
> 
> ```
> @Configuration
> public class MyConfiguration {
> 
>     @Bean
>     public WebMvcConfigurer corsConfigurer() {
>         return new WebMvcConfigurerAdapter() {
>             @Override
>             public void addCorsMappings(CorsRegistry registry) {
>                 registry.addMapping("/**");
>             }
>         };
>     }
> }
> ```
> 
> Ref. https://spring.io/blog/2015/06/08/cors-support-in-spring-framework

Yeah, this would also work. But controller level enabling is fine since we're pretty sure we'll have just one Controller class in this project. So `@CrossOrigin` annotation like below:

```
@CrossOrigin(origins = "*", allowedHeaders = "*")
@Controller
public class HomeController 
{
    @GetMapping(path="/")
    public String homeInit(Model model) {
        return "home";
    }
}
```

Any of them is fine really.

Ref: https://howtodoinjava.com/spring5/webmvc/spring-mvc-cors-configuration/
